site_name: Bilgi Yazılım Topluluğu
repo_url: https://github.com/bilgiyazilim/bilgiyazilim.github.io
repo_name: bilgiyazilim.github.io
site_url: https://bilgiyazilim.github.io
edit_uri: edit/main/docs/

nav:
  - Ana Sayfa: index.md
  - Hakkımızda: hakkimizda/index.md
  - Blog:
      - blog/index.md
  - Açık Ekran:
      - acik-ekran/index.md

theme:
  language: tr
  name: material
  palette:
    scheme: slate
    primary: black

  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.action.edit

  logo: assets/images/bilgi-yazilim-logo.png
  favicon: assets/images/bilgi-yazilim-logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - toc:
      permalink: true

plugins:
  - search
  - blog:
      post_date_format: long
      post_excerpt_max_authors: 3
      post_readtime_words_per_minute: 230
      pagination_per_page: 5
      pagination_format: "$link_previous ~2~ $link_next"
      categories_allowed:
        # Bu kuralı typo'ları engellemek için ekledik.
        # Yeni bir kategoride blog yazılacağı zaman kategori adını buraya eklemeyi unutmayın.
        - Genel
        - Yazılım
        - Açık Ekran
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      fallback_to_build_date: true
      locale: tr
      exclude:
        - index.md
        - hakkimizda/index.md
        - discord.md
  - social

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bilgiyazilim
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tTePne6hqN

# mkdocs-coverage (https://github.com/tylerdotrar/mkdocs-coverpage) (home.html belgesinde kullanılıyor)
# TODO: bu konfigürasyonlar mkdocs.yml'dan kaldırılıp home.html belgesinde hardcoded olarak kullanılacak.
# Custom Homepage Elements
home_cover_image: assets/images/bilgi-yazilim-logo.png
home_tagline: Bilgi Yazılım Topluluğu
home_description: |
  İstanbul Bilgi Üniversitesi'ndeki yazılımla ilgilenen öğrencilerin topluluğu

# Gradient Color
home_gradient_hsla: hsla(203deg, 43%, 21%, 1)

# Custom Homepage Button(s)
home_button1_name: Discord'a Katıl # Comment this parameter out to remove the button.
home_button1_url: discord/ # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people # Options: "people", "gear", "image"
home_button1_blurb: | # Short description of this button / section.
  Bu metin bloğu silindi

home_button2_name: Hakkımızda # Comment this parameter out to remove the button.
home_button2_url: hakkimizda/ # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear # Options: "people", "gear", "image"
home_button2_blurb: | # Short description of this button / section.
  Bu metin bloğu silindi

# home_button3_name: Clicky 3 # Comment this parameter out to remove the button.
home_button3_url: Folder3/ # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image # Options: "people", "gear", "image"
home_button3_blurb: | # Short description of this button / section.
  Bu metin bloğu silindi
